/*
drop INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL_IDSTATUS;
drop INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL;
drop INDEX ECOMMERCE.IX_PEDIDO_IDSTATUS;
*/

EXPLAIN PLAN FOR
    SELECT    COUNT(1)          
    FROM      ECOMMERCE.PEDIDO
    WHERE     VL_TOTAL = 100000
    AND       ID_STATUS = 4;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL ON ECOMMERCE.PEDIDO(VL_TOTAL);
CREATE BITMAP INDEX ECOMMERCE.IX_PEDIDO_IDSTATUS ON ECOMMERCE.PEDIDO(ID_STATUS);

-- veja qual dos indices criados anteriormente esta sendo usado:
EXPLAIN PLAN FOR
    SELECT    COUNT(1)          
    FROM      ECOMMERCE.PEDIDO
    WHERE     VL_TOTAL = 100000
    AND       ID_STATUS = 4;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE BITMAP INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL_IDSTATUS ON ECOMMERCE.PEDIDO(VL_TOTAL, ID_STATUS);

-- veja se agora o indice composto esta sendo usado:
EXPLAIN PLAN FOR
    SELECT    COUNT(1)          
    FROM      ECOMMERCE.PEDIDO
    WHERE     VL_TOTAL = 100000
    AND       ID_STATUS = 4;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- apague os indices criados:
drop INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL_IDSTATUS;
drop INDEX ECOMMERCE.IX_PEDIDO_VLTOTAL;
drop INDEX ECOMMERCE.IX_PEDIDO_IDSTATUS;

