-- Ao inves de:
EXPLAIN PLAN FOR                        
  SELECT      DISTINCT D.DEPARTMENT_ID,D.DEPARTMENT_NAME
  FROM        HR.DEPARTMENTS D 
  INNER JOIN  HR.EMPLOYEES E
      ON      D.DEPARTMENT_ID = E.DEPARTMENT_ID;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Ou ao inves de:
EXPLAIN PLAN FOR                        
  SELECT      D.DEPARTMENT_ID,D.DEPARTMENT_NAME
  FROM        HR.DEPARTMENTS D 
  INNER JOIN  HR.EMPLOYEES E
      ON      D.DEPARTMENT_ID = E.DEPARTMENT_ID
    GROUP BY  D.DEPARTMENT_ID,D.DEPARTMENT_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Escreva:
EXPLAIN PLAN FOR
  SELECT      D.DEPARTMENT_ID,D.DEPARTMENT_NAME
  FROM        HR.DEPARTMENTS D 
  WHERE       EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
                      WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);        