-- ao inves de:
EXPLAIN PLAN FOR      
  SELECT      E.FIRST_NAME,
              E.LAST_NAME,
              D.DEPARTMENT_NAME 
  FROM        HR.EMPLOYEES E
  INNER JOIN  HR.DEPARTMENTS D
        ON    E.DEPARTMENT_ID = D.DEPARTMENT_ID
  WHERE       E.EMPLOYEE_ID = 101;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);    

-- escreva:      
EXPLAIN PLAN FOR      
  SELECT      E.FIRST_NAME,
              E.LAST_NAME,
              (SELECT D.DEPARTMENT_NAME FROM HR.DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) DEPARTMENT_NAME
  FROM        HR.EMPLOYEES E
  WHERE       E.EMPLOYEE_ID = 101;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);