-- ** CTAS em Enterprise Edition pode usar paralelismo 

-- cria GTT para ter dados de origem de carga:
CREATE GLOBAL TEMPORARY TABLE ECOMMERCE.TMP_ITEM_PEDIDO2  on commit preserve rows AS 
SELECT * FROM ECOMMERCE.ITEM_PEDIDO
union all
SELECT * FROM ECOMMERCE.ITEM_PEDIDO
union all
SELECT * FROM ECOMMERCE.ITEM_PEDIDO
union all
SELECT * FROM ECOMMERCE.ITEM_PEDIDO
union all
SELECT * FROM ECOMMERCE.ITEM_PEDIDO;
COMMIT;

-- cria tabela destino dos dados:
CREATE TABLE ECOMMERCE.ITEM_PEDIDO2 AS SELECT * FROM ECOMMERCE.TMP_ITEM_PEDIDO2 WHERE 1=0;

-- bloco para testar CTAS:
SET SERVEROUTPUT ON
DECLARE 
  	L_START     NUMBER;    
    V_COUNT     NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ECOMMERCE.ITEM_PEDIDO2';

    L_START := DBMS_UTILITY.GET_TIME;
    -- executa insert direct path
    INSERT /*+ APPEND */ INTO ECOMMERCE.ITEM_PEDIDO2
    SELECT * FROM ECOMMERCE.TMP_ITEM_PEDIDO2;  
    -- Tempo de um insert convencional 
    DBMS_OUTPUT.PUT_LINE('INSERT direct path: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's');  -- 55,96s   
  
    EXECUTE IMMEDIATE 'drop TABLE ECOMMERCE.ITEM_PEDIDO2';

    -- Configure o otimizador para versao 11.2.0.4:
    execute immediate 'ALTER SESSION SET optimizer_features_enable = ''11.2.0.4''';   
    L_START := DBMS_UTILITY.GET_TIME;   
    -- executa CTAS
    EXECUTE IMMEDIATE 'CREATE TABLE ECOMMERCE.ITEM_PEDIDO2 AS SELECT * FROM ECOMMERCE.TMP_ITEM_PEDIDO2';   -- 40.17s
    DBMS_OUTPUT.PUT_LINE('CTAS c/ OFE 11.2.0.4: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's'); 
     -- Volta o otimizador para versao 12.2.0.1:
    
    EXECUTE IMMEDIATE 'ALTER SESSION SET optimizer_features_enable = ''12.2.0.1''';
    
    EXECUTE IMMEDIATE 'drop TABLE ECOMMERCE.ITEM_PEDIDO2';
    L_START := DBMS_UTILITY.GET_TIME;   
    EXECUTE IMMEDIATE 'CREATE TABLE ECOMMERCE.ITEM_PEDIDO2 AS SELECT * FROM ECOMMERCE.TMP_ITEM_PEDIDO2'; 
    DBMS_OUTPUT.PUT_LINE('CTAS c/ OFE 12.2.0.1: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's'); 
    
    EXECUTE IMMEDIATE 'drop TABLE ECOMMERCE.ITEM_PEDIDO2';
    L_START := DBMS_UTILITY.GET_TIME;   
    EXECUTE IMMEDIATE 'CREATE TABLE ECOMMERCE.ITEM_PEDIDO2 AS SELECT /*+ NO_GATHER_OPTIMIZER_STATISTICS */ * FROM ECOMMERCE.TMP_ITEM_PEDIDO2'; 
    DBMS_OUTPUT.PUT_LINE('CTAS c/ OFE 12.2.0.1 + hint NO_GATHER_OPTIMIZER_STATISTICS: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's'); 
END;