-- Ao inves de:
EXPLAIN PLAN FOR
  SELECT COUNT (*)
  FROM  HR.EMPLOYEES
  WHERE SALARY < 2000
  UNION ALL
  SELECT COUNT (*)
  FROM  HR.EMPLOYEES
  WHERE SALARY BETWEEN 2000 AND 4000
  UNION ALL
  SELECT COUNT (*)
  FROM  HR.EMPLOYEES
  WHERE SALARY>4000;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Escreva:
EXPLAIN PLAN FOR
  SELECT COUNT (CASE WHEN salary < 2000 
                     THEN 1 ELSE null END) count1, 
         COUNT (CASE WHEN salary BETWEEN 2001 AND 4000 
                     THEN 1 ELSE null END) count2, 
        COUNT (CASE WHEN salary > 4000 
                   THEN 1 ELSE NULL END) COUNT3 
  FROM  HR.EMPLOYEES; 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
