EXPLAIN PLAN FOR
    SELECT  P.DT_PEDIDO, I.CD_PRODUTO, COUNT(1) TOTAL_PRODUTOS
    FROM    ECOMMERCE.PEDIDO P
    JOIN    ECOMMERCE.ITEM_PEDIDO I
      ON    P.CD_PEDIDO = I.CD_PEDIDO
    GROUP BY    P.DT_PEDIDO, I.CD_PRODUTO;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);   