-- TESTANDO A PERFORMANCE DE PK VARCHAR2 X NUMBER

-- TESTE 1: criando a table para testes (CLIENTE3) com a coluna NUMBER
CREATE TABLE ECOMMERCE.CLIENTE3
  (
    CD_CLIENTE    NUMBER NOT NULL ENABLE PRIMARY KEY,
    NM_CLIENTE    CHAR(50 BYTE) NOT NULL ENABLE,
    ID_SEXO       CHAR(1 BYTE),
    TP_CLIENTE    NUMBER(1,0) NOT NULL ENABLE,
    NU_CPF_CGC    NUMBER(14,0) NOT NULL ENABLE,
    DT_NASCIMENTO DATE NOT NULL ENABLE,
    NM_EMAIL      CHAR(50 BYTE) NOT NULL ENABLE,
    NU_TELEFONE   NUMBER(10,0) NOT NULL ENABLE,
    NM_ENDERECO   CHAR(100 BYTE) NOT NULL ENABLE,
    NM_CIDADE     CHAR(50 BYTE) NOT NULL ENABLE,
    CD_UF         NUMBER NOT NULL ENABLE,
    DT_CADASTRO   DATE NOT NULL ENABLE,
    ID_STATUS     NUMBER(1,0) NOT NULL ENABLE,
    NU_CELULAR    NUMBER(10,0)
  );  
/

-- teste de performance de insercao de dados em NUMBER
SET SERVEROUTPUT ON
DECLARE
  L_START         NUMBER;    
BEGIN
  L_START := DBMS_UTILITY.GET_TIME;
  INSERT INTO ECOMMERCE.CLIENTE3 SELECT * FROM ECOMMERCE.CLIENTE;
  --INSERT INTO ECOMMERCE.CLIENTE3 SELECT * FROM ECOMMERCE.CLIENTE;
  --INSERT INTO ECOMMERCE.CLIENTE3 SELECT * FROM ECOMMERCE.CLIENTE;  
  DBMS_OUTPUT.PUT_LINE('Tempo total das inserção em NUMBER: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's');
  -- commita inserções
  COMMIT;    
END;
/

ANALYZE TABLE ECOMMERCE.CLIENTE3 COMPUTE STATISTICS;
/

-- teste de peformance de select em char
EXPLAIN PLAN FOR
 SELECT * FROM  ECOMMERCE.CLIENTE3 WHERE CD_CLIENTE between 1001 and 7000;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
/

SELECT  SUM(SUBSTR(DUMP(CD_CLIENTE),11,INSTR(DUMP(CD_CLIENTE),':')-11)) AS TOTAL_BYTES
FROM    ECOMMERCE.CLIENTE3;
/

-- TESTANDO A PERFORMANCE DE VARCHAR2
DROP TABLE ECOMMERCE.CLIENTE3 purge;
/

-- TESTE 2: criando a table para testes (CLIENTE3) com as colunas VARCHAR2
CREATE TABLE ECOMMERCE.CLIENTE4
  (
    CD_CLIENTE    VARCHAR2(15) NOT NULL ENABLE PRIMARY KEY,
    NM_CLIENTE    VARCHAR2(50 BYTE) NOT NULL ENABLE,
    ID_SEXO       VARCHAR2(1 BYTE),
    TP_CLIENTE    NUMBER(1,0) NOT NULL ENABLE,
    NU_CPF_CGC    NUMBER(14,0) NOT NULL ENABLE,
    DT_NASCIMENTO DATE NOT NULL ENABLE,
    NM_EMAIL      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    NU_TELEFONE   NUMBER(10,0) NOT NULL ENABLE,
    NM_ENDERECO   VARCHAR2(100 BYTE) NOT NULL ENABLE,
    NM_CIDADE     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CD_UF         NUMBER NOT NULL ENABLE,
    DT_CADASTRO   DATE NOT NULL ENABLE,
    ID_STATUS     NUMBER(1,0) NOT NULL ENABLE,
    NU_CELULAR    NUMBER(10,0)
  );  
/

-- teste de performance de insercao de dados em CHAR
SET SERVEROUTPUT ON
DECLARE
  L_START         NUMBER;    
BEGIN
  L_START := DBMS_UTILITY.GET_TIME;
  INSERT INTO ECOMMERCE.CLIENTE4 SELECT * FROM ECOMMERCE.CLIENTE;
  --INSERT INTO ECOMMERCE.CLIENTE3 SELECT * FROM ECOMMERCE.CLIENTE;
  --INSERT INTO ECOMMERCE.CLIENTE3 SELECT * FROM ECOMMERCE.CLIENTE;  
  DBMS_OUTPUT.PUT_LINE('Tempo total das inserção em VARCHAR2: ' || round((DBMS_UTILITY.GET_TIME - L_START)/100,2) || 's');
  -- commita inserções
  COMMIT;    
END;
/

ANALYZE TABLE ECOMMERCE.CLIENTE4 COMPUTE STATISTICS;
/

-- teste de peformance de select em VARCHAR2
EXPLAIN PLAN FOR
 SELECT * FROM  ECOMMERCE.CLIENTE4 WHERE to_number(CD_CLIENTE) between 1001 and 7000; 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
/

CREATE INDEX ECOMMERCE.IX_CLIENTE4_CDCLIENTE_TON ON ECOMMERCE.CLIENTE4(TO_NUMBER(CD_CLIENTE));
/
-- teste de peformance de select em VARCHAR2
EXPLAIN PLAN FOR
 SELECT * FROM  ECOMMERCE.CLIENTE4 WHERE to_number(CD_CLIENTE) between 1001 and 7000; 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
/

SELECT  SUM(SUBSTR(DUMP(CD_CLIENTE),11,INSTR(DUMP(CD_CLIENTE),':')-11)) AS TOTAL_BYTES
FROM    ECOMMERCE.CLIENTE4;
/

DROP TABLE ECOMMERCE.CLIENTE4 PURGE;
/
