CREATE TABLE "ECOMMERCE"."CATEGORIA"
  (
    "CD_CATEGORIA" NUMBER,
    "NM_CATEGORIA" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "DS_CATEGORIA" VARCHAR2(200 BYTE),
    CONSTRAINT "UK_CATEGORIA_NMPRODUTO" UNIQUE ("NM_CATEGORIA"),
    CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("CD_CATEGORIA")
  ) tablespace ecommerce_d;
  
  CREATE TABLE "ECOMMERCE"."CLIENTE"
  (
    "CD_CLIENTE" NUMBER NOT NULL ENABLE,
    "NM_CLIENTE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ID_SEXO"    CHAR(1 BYTE) NOT NULL ENABLE,
    "TP_CLIENTE" NUMBER(1,0) NOT NULL ENABLE,
    "NU_CPF_CGC" NUMBER(14,0) NOT NULL ENABLE,
    "DT_NASCIMENTO" DATE NOT NULL ENABLE,
    "NM_EMAIL"    VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "NU_TELEFONE" NUMBER(10,0) NOT NULL ENABLE,
    "NM_ENDERECO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "NM_CIDADE"   VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ID_UF"       NUMBER NOT NULL ENABLE,
    "DT_CADASTRO" DATE NOT NULL ENABLE,
    "ID_STATUS"  NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
    "NU_CELULAR" NUMBER(10,0),
    CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("CD_CLIENTE") ,
    CONSTRAINT "UK_CLIENTE_NMCLIENTE" UNIQUE ("NM_CLIENTE"),
    CONSTRAINT "CK_CLIENTE_IDSEXO" CHECK (ID_SEXO       = 'M'
  OR ID_SEXO                                             = 'F') ENABLE,
    CONSTRAINT "CK_CLIENTE_STATUS" CHECK (ID_STATUS     = 1
  OR ID_STATUS                                           = 2) ENABLE,
    CONSTRAINT "CK_CLIENTE_TPCLIENTE" CHECK (TP_CLIENTE = '1'
  OR TP_CLIENTE                                          = '2') ENABLE
  )  tablespace ecommerce_d;
COMMENT ON COLUMN "ECOMMERCE"."CLIENTE"."TP_CLIENTE"
IS
  'Valores: 1=PF, 2= PJ.';
  COMMENT ON COLUMN "ECOMMERCE"."CLIENTE"."ID_STATUS"
IS
  'Valores: 1=''ativo'', 2=''inativo''';
  
  
  CREATE TABLE "ECOMMERCE"."PRODUTO"
  (
    "CD_PRODUTO"   NUMBER NOT NULL ENABLE,
    "NM_PRODUTO"   VARCHAR2(50 BYTE),
    "CD_CATEGORIA" NUMBER,
    "DS_PRODUTO"   VARCHAR2(200 BYTE),
    "VL_UNITARIO"  NUMBER(7,2),
    "QT_ESTOQUE"   NUMBER DEFAULT 0,
    "ID_STATUS"    NUMBER,
    CONSTRAINT "PK_PRODUTO" PRIMARY KEY ("CD_PRODUTO"),
    CONSTRAINT "UK_PRODUTO_NMPRODUTO" UNIQUE ("NM_PRODUTO"),
    CONSTRAINT "FK_PRODUTO_CATEGORIA" FOREIGN KEY ("CD_CATEGORIA") REFERENCES "ECOMMERCE"."CATEGORIA" ("CD_CATEGORIA") ENABLE
  )  tablespace ecommerce_d;

  
CREATE TABLE "ECOMMERCE"."UF"
  (
    "CD_UF" NUMBER NOT NULL ENABLE,
    "NM_UF" CHAR(2 BYTE) NOT NULL ENABLE,
    "DS_UF" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_UF" PRIMARY KEY ("CD_UF"),
    CONSTRAINT "UK_UF_NMUF" UNIQUE ("NM_UF")
  ) tablespace ecommerce_d;
    
CREATE TABLE "ECOMMERCE"."PEDIDO"
  (
    "CD_PEDIDO"  NUMBER NOT NULL ENABLE,
    "CD_CLIENTE" NUMBER NOT NULL ENABLE,
    "DT_PEDIDO" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "VL_TOTAL"    NUMBER(9,2) NOT NULL ENABLE,
    "ID_STATUS"   NUMBER NOT NULL ENABLE,
    "VL_DESCONTO" NUMBER(9,2),
    CONSTRAINT "PK_PEDIDO" PRIMARY KEY ("CD_PEDIDO"),
    CONSTRAINT "FK_PEDIDO_CLIENTE" FOREIGN KEY ("CD_CLIENTE") REFERENCES "ECOMMERCE"."CLIENTE" ("CD_CLIENTE")
  ) tablespace ecommerce_d  ;
COMMENT ON COLUMN "ECOMMERCE"."PEDIDO"."ID_STATUS"
IS 
  'Valores: 1=''Em análise'', 2=''Aguardando aprovação de crédito'', 3=''Enviado para a transportadora'', 4=''Entregue'', 5=''Cancelado''';
  
   
 CREATE TABLE "ECOMMERCE"."ITEM_PEDIDO"
  (
    "CD_PEDIDO"  NUMBER NOT NULL ENABLE,
    "CD_PRODUTO" NUMBER NOT NULL ENABLE,
    "QT_ITEM"    NUMBER NOT NULL ENABLE,
    "VL_TOTAL"   NUMBER(10,2) NOT NULL ENABLE,
    CONSTRAINT "PK_ITEM_PEDIDO" PRIMARY KEY ("CD_PEDIDO", "CD_PRODUTO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "ECOMMERCE_I" ENABLE,
    CONSTRAINT "FK_ITEMPEDIDO_PEDIDO" FOREIGN KEY ("CD_PEDIDO") REFERENCES "ECOMMERCE"."PEDIDO" ("CD_PEDIDO") ENABLE,
    CONSTRAINT "FK_ITEMPEDIDO_PRODUTO" FOREIGN KEY ("CD_PRODUTO") REFERENCES "ECOMMERCE"."PRODUTO" ("CD_PRODUTO") ENABLE
  ) tablespace ecommerce_d;