Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('1','AC','ACRE');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('2','AL','ALAGOAS');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('3','AP','AMAPÁ');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('4','AM','AMAZONAS');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('5','BA','BAHIA');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('6','CE','CEARÁ');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('7','DF','DISTRITO FEDERAL');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('8','ES','ESPÍRITO SANTO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('10','GO','GOIÁS');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('11','MA','MARANHÃO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('12','MT','MATO GROSSO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('13','MS','MATO GROSSO DO SUL');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('14','MG','MINAS GERAIS');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('15','NI','NÃO INFORMADO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('16','PR','PARANÁ');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('17','PB','PARAÍBA');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('18','PA','PARÁ');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('19','PE','PERNAMBUCO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('20','PI','PIAUÍ');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('21','RJ','RIO DE JANEIRO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('22','RN','RIO GRANDE DO NORTE');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('23','RS','RIO GRANDE DO SUL');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('24','RO','RONDÔNIA');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('25','RR','RORAIMA');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('26','SC','SANTA CATARINA');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('27','SE','SERGIPE');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('28','SP','SÃO PAULO');
Insert into ECOMMERCE.UF (CD_UF,NM_UF,DS_UF) values ('29','TO','TOCANTINS');
COMMIT;