-- ENTREGUES C/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..178345
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            4, ROUND(DBMS_RANDOM.VALUE(1,300),2)
      );          
  END LOOP;
  COMMIT;
END;
/
-- ENTREGUES S/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..392345
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            4, 0);          
  END LOOP;
  COMMIT;
END;
/
-- EM ANALISE C/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..1783
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            1, ROUND(DBMS_RANDOM.VALUE(1,300),2)
      );          
  END LOOP;
  COMMIT;
END;
/
-- EM ANALISE  S/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..5233
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            1, 0);          
  END LOOP;
  COMMIT;
END;
/
-- AGUARDANDO APROVACAO CREDITO C/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..3621
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            2, ROUND(DBMS_RANDOM.VALUE(1,300),2)
      );          
  END LOOP;
  COMMIT;
END;
/
-- AGUARDANDO APROVACAO CREDITO S/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..8233
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            2, 0);          
  END LOOP;
  COMMIT;
END;
/
-- ENVIADO PARA A TRANSPORTADORA C/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..956
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            3, ROUND(DBMS_RANDOM.VALUE(1,300),2)
      );          
  END LOOP;
  COMMIT;
END;
/
-- ENVIADO PARA A TRANSPORTADORA S/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..1823
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            3, 0);          
  END LOOP;
  COMMIT;
END;
/
-- CANCELADO C/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..369
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            5, ROUND(DBMS_RANDOM.VALUE(1,300),2)
      );          
  END LOOP;
  COMMIT;
END;
/
-- ENVIADO PARA A TRANSPORTADORA S/ DESCONTO (SEM VALOR TOTAL)
BEGIN
  FOR I IN 1..132
  LOOP
    INSERT INTO ECOMMERCE.PEDIDO VALUES
      (
        ECOMMERCE.SQ_PEDIDO.NEXTVAL, TRUNC(DBMS_RANDOM.VALUE(4,64073)), SYSDATE - (TRUNC(DBMS_RANDOM.VALUE(0, 1000))), 0,
            5, 0);          
  END LOOP;
  COMMIT;
END;
/