-- CONSULTA REALIZADA 1X POR DIA. NAO HA NECESSIDADE DE RETORNAR DADOS DO MES ATUAL. O SISTEMA QUE CHAMA ESTE SQL EH DE TERCEIRO E O SQL NAO TEM COMO SER ALTERADO:

-- otimize o SQL abaixo retornando exatamente os mesmos dados do SQL original:
SELECT      TO_CHAR(O.ORDER_DATE, 'YYYY/MM') AS ANO_MES,
            COUNT(O.ORDER_ID) AS QTDE_VENDAS,
            SUM(O.ORDER_TOTAL) AS VALOR_TOTAL_VENDAS,            
            O.CUSTOMER_CLASS
FROM        SOE.ORDERS O    
GROUP BY    TO_CHAR(O.ORDER_DATE, 'YYYY/MM'), O.CUSTOMER_CLASS
ORDER BY    ANO_MES, VALOR_TOTAL_VENDAS, QTDE_VENDAS, CUSTOMER_CLASS;  