OPTIONS (SILENT=ALL, DIRECT=TRUE)
UNRECOVERABLE LOAD DATA 
CHARACTERSET WE8ISO8859P1
INFILE 'item_pedido.dsv'
INSERT INTO TABLE ECOMMERCE.ITEM_PEDIDO3
TRUNCATE FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '"'
(   
    cd_pedido, 
    cd_produto, 
    qt_item,
    vl_total
)
