-- Ao  inves de:
SELECT        ECOMMERCE.PEDIDO.CD_PEDIDO,
              DT_PEDIDO,
              QT_ITEM,
              ECOMMERCE.PEDIDO.VL_TOTAL
FROM          ECOMMERCE.PEDIDO
INNER JOIN    ECOMMERCE.ITEM_PEDIDO I
      ON      ECOMMERCE.PEDIDO.CD_PEDIDO = I.CD_PEDIDO
WHERE         ECOMMERCE.PEDIDO.CD_PEDIDO = 253;

-- Escreva:
SELECT        P.CD_PEDIDO,
              P.DT_PEDIDO,
              IP.QT_ITEM,
              P.VL_TOTAL
FROM          ECOMMERCE.PEDIDO P
INNER JOIN    ECOMMERCE.ITEM_PEDIDO IP
        ON    P.CD_PEDIDO = IP.CD_PEDIDO
WHERE         P.CD_PEDIDO = 253;
