UPDATE  ECOMMERCE.CLIENTE
SET     NU_CELULAR = 99998888
WHERE   ROWNUM < 64000;
COMMIT;

CREATE INDEX ECOMMERCE.IX_CLIENTE_NUCELULAR ON ECOMMERCE.CLIENTE(NU_CELULAR);
/
-- PE em que a instrucao abaixo nao utiliza o indice criado na coluna NU_CELULAR:
EXPLAIN PLAN FOR
    SELECT      *
    FROM        ECOMMERCE.CLIENTE
    WHERE       NU_CELULAR IS NULL;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Analise o indice e veja que nao ha nenhuma linha indexada na coluna NU_CELULAR, pois ela so contem valores nulos:
ANALYZE INDEX ECOMMERCE.IX_CLIENTE_NUCELULAR COMPUTE STATISTICS;
ANALYZE INDEX ECOMMERCE.IX_CLIENTE_NUCELULAR VALIDATE STRUCTURE;

--- INDEX_STATS so contem detalhes da estrutura de BTREE 
SELECT * FROM INDEX_STATS;

-- APAGUE  e recrie o indice como BITMAP:
DROP INDEX ECOMMERCE.IX_CLIENTE_NUCELULAR;
CREATE BITMAP INDEX ECOMMERCE.ix_cliente_nucelular ON ECOMMERCE.CLIENTE(nu_celular);
EXEC DBMS_STATS.GATHER_TABLE_STATS('ECOMMERCE','CLIENTE');

-- teste novamente e veja se agora utiliza indice na consulta
EXPLAIN PLAN FOR
    SELECT      *
    FROM        ECOMMERCE.CLIENTE
    WHERE       NU_CELULAR IS NULL;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


