-- Ao inves de:
EXPLAIN PLAN FOR                        
  SELECT      D.DEPARTMENT_ID,D.DEPARTMENT_NAME
  FROM        HR.DEPARTMENTS D 
  INNER JOIN  HR.EMPLOYEES E
      ON      D.DEPARTMENT_ID = E.DEPARTMENT_ID
  CONNECT BY level <= 3
  ORDER BY    2 desc, 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Escreva:
EXPLAIN PLAN FOR
  SELECT      D.DEPARTMENT_ID,D.DEPARTMENT_NAME
  FROM        HR.DEPARTMENTS D 
  INNER JOIN  HR.EMPLOYEES E
      ON      D.DEPARTMENT_ID = E.DEPARTMENT_ID
  CONNECT BY level <= 3;    
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);        